language: python
python:
  - "3.6"

install: 
  - "pip install -r requirements_python.txt"
  - curl -L "http://code.google.com/p/shunit2/downloads/detail?name=shunit2-2.1.6.tgz" | tar zx


script:
    - python generate_map.py && bash tests/testing_map.sh


